@startuml
'https://plantuml.com/class-diagram



Class Main{
+main()
}

package persistence
{
    Class ConnenctionPool{
        {static}+ConnenctionPool instance
        {static}+HikariDataSource
        -ConnenctionPool()
        +ConnenctionPool getInstance()
        +synchronized Connection getConnection()
         {static}+HikariDataSource createHikariConnectionPool()
        }
}

package exceptions
{
    Class DatabseException< extends Exception>{
    + DatabaseException()
    + DatabaseException()
    }
}

package entities
{
    Class Material{
    -int materialId
    -String description
    -int length
    -int height
    -int width
    -int quantity
    -String unit
    -String type

    +Material()

    +int getMaterialId()
    +String getDescription()
    +int getLength()
    +int getHeight()
    +int getWidth()
    +int getQuantity()
    +String getUnit()
    +String getType()
    +String toString()



    }
}

package controllers
{
    Class MaterialController
}

package config
{
    Class SessionConfig{
    {static}+TemplateEngine templateEngine()
    }

    Class ThymeleafConfig{
    {static}+SessionHandler sessionConfig()
    }
}



@enduml